Transfer a file to your server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -2,8 +2,8 @@
 
 # Check if less than 4 parameters are provided
 if [ "$#" -lt 4 ]; then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY "
-    exit 1
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY "
+	exit 1
 fi
 
 # Assign parameters to variables
@@ -17,7 +17,7 @@ scp -o "StrictHostKeyChecking=no" -i "$ssh_key_path" "$file_path" "$username@$se
 
 # Check the exit status of scp command
 if [ $? -eq 0 ]; then
-    echo "File transfer successful"
+	echo "File transfer successful"
 else
-    echo "File transfer failed"
+	echo "File transfer failed"
 fi
